sudo: required
dist: trusty

## Enable container-based infrastructure
# sudo: false

language: python

python:
    - '2.7'

virtualenv:
  system_site_packages: true

before_install:
  # apt-install the dependencies which would otherwise take too long to
  # install.
  # for numpy >= 1.10
  # TODO use a backports repo
  - sudo apt-add-repository -y ppa:nschloe/numpy-nightly
  - sudo apt-add-repository -y ppa:fenics-packages/fenics
  - sudo apt-get update -qq
  - sudo apt-get -y install python-matplotlib python-mshr python-numpy python-scipy
  #
  - sudo -H pip install pytest pytest-cov
  # There's a bug in coeff() in 0.7.4, and another one in 1.0;
  # <https://github.com/sympy/sympy/issues/12132>.
  - sudo -H pip install sympy==0.7.6.1
  # PyAMG 3.* can't cope with nightly NumPy
  - sudo -H pip install "pyamg<3"

install:
  # Work around travis bug <https://github.com/travis-ci/travis-ci/issues/4948>
  - export PATH="/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.5.1.linux.amd64/bin:/home/travis/.local/bin:/usr/local/rvm/gems/ruby-2.2.3/bin:/usr/local/rvm/gems/ruby-2.2.3@global/bin:/usr/local/rvm/rubies/ruby-2.2.3/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v4.1.2/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/usr/local/rvm/bin"
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - sudo -H pip install .

script:
  - cd examples && pytest
  - cd tests && pytest --cov pyfvm

after_success:
  - bash <(curl -s https://codecov.io/bash)
