language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
  system_site_packages: true

## Enable container-based infrastructure
# sudo: false

# install dependencies
addons:
  apt:
    packages:
      - python-scipy
      - python-vtk

install:
  - pip install coveralls
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# command to run tests
script:
  - nosetests --with-coverage --cover-package=voropy

after_success:
  - coveralls
