language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-vtk
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then ln -s /usr/lib/pymodules/python2.6/vtk ~/virtualenv/python2.6/lib/python2.6/site-packages/; fi"
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ln -s /usr/lib/pymodules/python2.7/vtk ~/virtualenv/python2.7/lib/python2.7/site-packages/; fi"
virtualenv:
  system_site_packages: true
install:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
# command to run tests
script:
    - "python tests/cv_tests.py"
    - "python tests/gradient_test.py"

#before_install:
#    # install numpy for python 3.2 (currently not installed in travis)
#    - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then sudo apt-get install python3-numpy 2>&1 | tail -n 2; fi"
#    - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then ln -s /usr/lib/python3/dist-packages/numpy ~/virtualenv/python3.2/lib/python3.2/site-packages/; fi"
#    # install scipy for python 3.2
#    - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then sudo apt-get install python3-scipy 2>&1 | tail -n 2; fi"
#    - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then ln -s /usr/lib/python3/dist-packages/scipy ~/virtualenv/python3.2/lib/python3.2/site-packages/; fi"
#    # install scipy for python 2.7
#    - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install python-scipy 2>&1 | tail -n 2; fi"
#    - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ln -s /usr/lib/python2.7/dist-packages/scipy ~/virtualenv/python2.7/lib/python2.7/site-packages/; fi"
#script: "python -m krypy.tests.tests"
