sudo: required
dist: trusty

## Enable container-based infrastructure
# sudo: false

language: python

python:
    - "2.7"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-scipy python-vtk
  - sudo apt-get install pandoc

install:
  - pip install coveralls
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# command to run tests
script:
  - nosetests --with-coverage --cover-package=voropy

after_success:
  - coveralls
