language: python
python:
    - "2.7"
virtualenv:
  system_site_packages: true
# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-vtk
install:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
# command to run tests
script:
    - python tests/cv_tests.py
    - python tests/gradient_test.py
