version: 2

jobs:
  build:
    working_directory: ~/pyfvm/
    docker:
      - image: ubuntu:17.04
    steps:
      - run: apt-get update
      - run: apt-get install -y software-properties-common
      # For python3-vtk7
      - run: LANG=C.UTF-8 apt-add-repository -y ppa:nschloe/vtk7-nightly
      # For various sympy bugs, e.g., <https://github.com/sympy/sympy/issues/12132>:
      - run: LANG=C.UTF-8 apt-add-repository -y ppa:nschloe/sympy-nightly
      - run: apt-get update
      - run: apt-get -y install python3-matplotlib
      - run: apt-get -y install python3-numpy
      - run: apt-get -y install python3-scipy
      - run: apt-get -y install python3-vtk7
      - run: apt-get -y install python3-sympy  # takes forever b/c of texlive
      - run: apt-get -y install python3-pip
      - run: apt-get -y install gmsh
      - run: pip3 install -U pytest pytest-cov pyamg
      - checkout
      - run: LANG=C.UTF-8 pip3 install .
      # The actual test
      - run: cd ~/pyfvm/examples/ && pytest
      - run: cd ~/pyfvm/tests/ && pytest --cov pyfvm
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
