version: 2

jobs:
  build:
    working_directory: ~/work/
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip gmsh
      - run: pip3 install -U pytest pytest-cov excode black flake8
      - checkout
      - run: LANG=C.UTF-8 pip3 install .
      - run: LANG=C.UTF-8 pip3 install -r test_requirements.txt
      # format and lint
      - run: LC_ALL=C.UTF-8 black --check setup.py pyfvm/ test/*.py
      - run: flake8 setup.py pyfvm/ test/*.py
      # The actual test
      - run: excode README.md test/readme_test.py --filter python,test
      # OMPI doesn't work in chroot by default, cf.
      # <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=494046>
      - run: cd test/ && OMPI_MCA_plm_rsh_agent=/bin/false pytest ../examples . --cov pyfvm
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
